### ISSUE TITLE
パッケージが見つからない

### ISSUE THREAD

**Issue by buzzshima** [open-rdc/navigation_dojo#22]
毎回ビルドしないとコンパイルできない時はパスが間違っている可能性がある

**Comment by DaikiMaekawa** [comment]
ワークスペースのパスを確認すること

**Comment by DaikiMaekawa** [comment]
.bashrcに設定する

**Comment by Hiroki-Goto** [comment]
.bashrcに
sorce /home/<ユーザーネーム>/catkin_ws/devel/setup.bash
を設定したら直りました
